apiVersion: v1
kind: Service
metadata:
  name: kubeconfig-generator
  labels:
    app: kubeconfig-generator
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - name: ui
    port: 9090
    protocol: TCP
  - name: api
    port: 8080
    protocol: TCP
  selector:
    app: kubeconfig-generator
